2025-05-12 22:13:20,946 [ERROR] Błąd aplikacji: Niepoprawny format daty '2003-12-65'. Wprowadź w formacie RRRR-MM-DD.
Traceback (most recent call last):
  File "c:\Users\kirla\Workspace\Studies\Python\JPWP\project_root\trip_app\input_validation.py", line 11, in parse_date
    date = datetime.datetime.strptime(date_str, "%Y-%m-%d").date()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kirla\AppData\Local\Programs\Python\Python313\Lib\_strptime.py", line 674, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kirla\AppData\Local\Programs\Python\Python313\Lib\_strptime.py", line 456, in _strptime
    raise ValueError("unconverted data remains: %s" %
                      data_string[found.end():])
ValueError: unconverted data remains: 5

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\kirla\Workspace\Studies\Python\JPWP\project_root\main.py", line 50, in main
    date = parse_date(date_str)  # może zgłosić TripError
  File "c:\Users\kirla\Workspace\Studies\Python\JPWP\project_root\trip_app\input_validation.py", line 14, in parse_date
    raise TripError(f"Niepoprawny format daty '{date_str}'. Wprowadź w formacie RRRR-MM-DD.") from e
trip_app.exceptions.TripError: Niepoprawny format daty '2003-12-65'. Wprowadź w formacie RRRR-MM-DD.
2025-05-12 22:13:54,095 [ERROR] Nieoczekiwany błąd programu.
Traceback (most recent call last):
  File "c:\Users\kirla\Workspace\Studies\Python\JPWP\project_root\main.py", line 136, in main
    pdb.set_trace()  # pułapka debuggera; po uruchomieniu można badać stan programu
    ~~~~~~~~~~~~~^^
  File "C:\Users\kirla\AppData\Local\Programs\Python\Python313\Lib\bdb.py", line 116, in trace_dispatch
    return self.dispatch_opcode(frame, arg)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\kirla\AppData\Local\Programs\Python\Python313\Lib\bdb.py", line 216, in dispatch_opcode
    if self.quitting: raise BdbQuit
                      ^^^^^^^^^^^^^
bdb.BdbQuit
2025-05-12 22:14:26,030 [INFO] Utworzono nową wycieczkę: Po prostu w dniu 2025-12-03
2025-05-12 22:14:45,544 [ERROR] Błąd aplikacji: Nie znaleziono uczestnika o email: kirlanby
Traceback (most recent call last):
  File "c:\Users\kirla\Workspace\Studies\Python\JPWP\project_root\main.py", line 70, in main
    trip.remove_participant(email)  # może zgłosić ParticipantNotFoundError
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "c:\Users\kirla\Workspace\Studies\Python\JPWP\project_root\trip_app\trip.py", line 33, in remove_participant
    raise ParticipantNotFoundError(f"Nie znaleziono uczestnika o email: {email}")
trip_app.exceptions.ParticipantNotFoundError: Nie znaleziono uczestnika o email: kirlanby
2025-05-12 22:15:05,199 [INFO] Zapisano wycieczkę do pliku text.json
2025-05-12 22:15:51,463 [INFO] Dodano uczestnika o email kirlanby@gmail,com
2025-05-12 22:21:33,358 [ERROR] Błąd aplikacji: Data wyjazdu nie może być z przeszłości.
Traceback (most recent call last):
  File "c:\Users\kirla\Workspace\Studies\Python\JPWP\project_root\main.py", line 44, in main
    date = parse_date(date_str)
  File "c:\Users\kirla\Workspace\Studies\Python\JPWP\project_root\trip_app\input_validation.py", line 17, in parse_date
    raise TripError("Data wyjazdu nie może być z przeszłości.")
trip_app.exceptions.TripError: Data wyjazdu nie może być z przeszłości.
2025-05-12 22:22:08,686 [INFO] Utworzono wycieczkę: Popa (2027-12-12)
2025-05-12 22:23:08,884 [INFO] Dodano uczestnika ki do wycieczki 'Popa'
2025-05-12 22:23:26,885 [INFO] Zapisano 'Popa' do pliku l
2025-05-12 22:23:52,901 [ERROR] Błąd aplikacji: Nie znaleziono uczestnika o email: kirla
Traceback (most recent call last):
  File "c:\Users\kirla\Workspace\Studies\Python\JPWP\project_root\main.py", line 110, in main
    t.remove_participant(email)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "c:\Users\kirla\Workspace\Studies\Python\JPWP\project_root\trip_app\trip.py", line 33, in remove_participant
    raise ParticipantNotFoundError(f"Nie znaleziono uczestnika o email: {email}")
trip_app.exceptions.ParticipantNotFoundError: Nie znaleziono uczestnika o email: kirla
